# Generated by Django 5.2.3 on 2025-07-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_updated_by_alter_client_created_by_and_more'),
        ('tasks', '0002_task_updated_by_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job'),
        ),
    ]
